#!/usr/bin/env python
import sys
import re
import warnings
from pathlib import Path

from ai_software_factory.crew import AiSoftwareFactory

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")


def markdown_to_docx(md_path: str, docx_path: str):
    """Convert a markdown SRS file to a formatted Word document."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    md_text = Path(md_path).read_text(encoding="utf-8")
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Title page
    doc.add_paragraph()
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run('Software Requirement Specification (SRS)')
    run.bold = True
    run.font.size = Pt(26)
    run.font.color.rgb = RGBColor(0, 51, 102)

    doc.add_paragraph()
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run('Generated by AI Software Factory Pipeline')
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_page_break()

    # Parse markdown line by line
    in_code_block = False
    code_lines = []

    for line in md_text.split('\n'):
        stripped = line.strip()

        # Code block toggle
        if stripped.startswith('```'):
            if in_code_block:
                # End code block - add collected code
                code_para = doc.add_paragraph()
                code_run = code_para.add_run('\n'.join(code_lines))
                code_run.font.name = 'Courier New'
                code_run.font.size = Pt(9)
                code_para.paragraph_format.left_indent = Inches(0.5)
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        # Headings
        if stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('#### '):
            doc.add_heading(stripped[5:], level=4)
        # Table rows
        elif stripped.startswith('|') and not all(c in '|-: ' for c in stripped):
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            para = doc.add_paragraph()
            para.paragraph_format.left_indent = Inches(0.3)
            para.add_run('  |  '.join(cells)).font.size = Pt(10)
        elif stripped.startswith('|') and all(c in '|-: ' for c in stripped):
            continue  # Skip table separator lines
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        # Numbered lists
        elif re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            doc.add_paragraph(text, style='List Number')
        # Bold lines
        elif stripped.startswith('**') and stripped.endswith('**'):
            para = doc.add_paragraph()
            run = para.add_run(stripped.strip('*'))
            run.bold = True
        # Empty lines
        elif not stripped:
            continue
        # Normal text
        else:
            doc.add_paragraph(stripped)

    doc.save(docx_path)
    print(f"\n✅ SRS Word document saved to: {docx_path}")


def run():
    inputs = {
        'project_idea': (
            'Build a School Attendance Management System. '
            'Features: teacher marks attendance, student attendance dashboard, '
            'monthly attendance reports.'
        )
    }
    try:
        AiSoftwareFactory().crew().kickoff(inputs=inputs)
        # Convert SRS markdown to Word document
        srs_md = 'output/01_srs.md'
        srs_docx = 'output/01_srs.docx'
        if Path(srs_md).exists():
            markdown_to_docx(srs_md, srs_docx)
    except Exception as e:
        raise Exception(f"An error occurred while running the crew: {e}")


def train():
    inputs = {
        'project_idea': (
            'Build a School Attendance Management System. '
            'Features: teacher marks attendance, student attendance dashboard, '
            'monthly attendance reports.'
        )
    }
    try:
        AiSoftwareFactory().crew().train(
            n_iterations=int(sys.argv[1]),
            filename=sys.argv[2],
            inputs=inputs
        )
    except Exception as e:
        raise Exception(f"An error occurred while training the crew: {e}")


def replay():
    try:
        AiSoftwareFactory().crew().replay(task_id=sys.argv[1])
    except Exception as e:
        raise Exception(f"An error occurred while replaying the crew: {e}")


def test():
    inputs = {
        'project_idea': (
            'Build a School Attendance Management System. '
            'Features: teacher marks attendance, student attendance dashboard, '
            'monthly attendance reports.'
        )
    }
    try:
        AiSoftwareFactory().crew().test(
            n_iterations=int(sys.argv[1]),
            eval_llm=sys.argv[2],
            inputs=inputs
        )
    except Exception as e:
        raise Exception(f"An error occurred while testing the crew: {e}")
